### ISSUE TITLE
vscode: Using "Selection->Expand Selection" selects wrong scope

### ISSUE THREAD

**Issue by fkoehler** [scala/vscode-scala-syntax#49] opened 2019-09-04 11:56 UTC
I am not sure if this issue belongs to this repo or should live somewhere else. I am using metals with vscode and find the expand selection for scala code to be quite greedy. Here is an example snippet:

```scala
object Test {
  val foo = "bar"
  def call(s: String, s: String): Unit = ???
}

object Scope {
  Test.call(Test.foo, Test.foo)
}
```

Putting the cursor on the `Test` object name inside the `Test.call` call and using `Selection->Expand Selection` it selects first the `Test` object which is correct, but then the entire parentheses block and not just the member `foo`.

Result:
![image](https://user-images.githubusercontent.com/943818/64252657-d8361380-cf1b-11e9-8e6d-2bbc0515bbce.png)

Expected:
![image](https://user-images.githubusercontent.com/943818/64252698-f3088800-cf1b-11e9-87e0-ec3a7ae2a452.png)

If it is in this repo where is a starting point to look? Maybe I can figure the error out

**Comment by nicolasstucki** [comment] 2019-09-17 13:16
This is probably an issue with the language sever. Check the issue could come from
* https://github.com/scalameta/metals
* https://github.com/lampepfl/dotty/tree/master/vscode-dotty

**Comment by nicolasstucki** [comment] 2019-09-17 13:19
Otherwise could be related with https://github.com/scala/vscode-scala-syntax/blob/master/language-configuration.json

**Comment by doofin** [comment] 2022-02-06 23:02
This is quite annoying,do we have any updates now?

**Comment by Jentsch** [comment] 2024-10-08 10:52
I think this issue can be closed. It seems to be a duplicate of scalameta/metals#3615 that is closed. *With metals running* I can not reproduce the issue.

**Closed** 2024-10-08 11:46 UTC
Labels: enhancement
